/**
 * Bundle the Worker into a single file.
 *
 * The output is committed so the Worker can be deployed by pasting it into the
 * Cloudflare dashboard's code editor, which is the route available when the
 * repository owner cannot connect a Git integration. `wrangler deploy` does its
 * own bundling and ignores this file, so both routes stay available.
 */
import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outfile = resolve(root, 'dist/worker.js');

await mkdir(dirname(outfile), { recursive: true });

const result = await build({
  entryPoints: [resolve(root, 'src/worker/index.ts')],
  outfile,
  bundle: true,
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  // Readable rather than minified: this file is pasted into a dashboard editor
  // by hand, and a single unreadable line is hostile to anyone inspecting it.
  minify: false,
  sourcemap: false,
  legalComments: 'none',
  banner: {
    js: [
      '// berkhamsted-reading-signature',
      '// Generated by `npm run build` from src/worker/. Do not edit directly.',
      '// Paste this whole file into the Cloudflare dashboard Worker editor,',
      '// or deploy from source with `npx wrangler deploy`.',
    ].join('\n'),
  },
  metafile: true,
});

const bytes = (await readFile(outfile)).byteLength;
const warnings = result.warnings ?? [];

for (const warning of warnings) {
  console.warn(`warning: ${warning.text}`);
}

await writeFile(
  resolve(root, 'dist/.build-info'),
  `built ${new Date().toISOString()}\nbytes ${bytes}\n`,
);

console.log(`Bundled worker: ${(bytes / 1024).toFixed(1)} kB -> dist/worker.js`);

if (bytes > 900_000) {
  console.error('Bundle is unexpectedly large; check for an accidental dependency.');
  process.exit(1);
}
