/**
 * Bundle the Worker.
 *
 * Two outputs, both committed:
 *
 *   dist/worker.js      readable, for `wrangler deploy` and Workers Builds.
 *   dist/worker.min.js  minified, for pasting into the Cloudflare dashboard
 *                       editor when no Git integration is available.
 *
 * The minified build is not about size. A copy-paste that strips newlines has
 * already destroyed this project's SQL once, and the same thing would happen to
 * the readable bundle: everything after its first `//` comment would become one
 * comment. Minified output carries no line comments, so it survives.
 */
import { build } from 'esbuild';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outfile = resolve(root, 'dist/worker.js');
const minifiedFile = resolve(root, 'dist/worker.min.js');

await mkdir(dirname(outfile), { recursive: true });

const shared = {
  entryPoints: [resolve(root, 'src/worker/index.ts')],
  bundle: true,
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  sourcemap: false,
  legalComments: 'none',
};

const result = await build({
  ...shared,
  outfile,
  minify: false,
  banner: {
    js: [
      '// berkhamsted-reading-signature',
      '// Generated by `npm run build` from src/worker/. Do not edit directly.',
      '// Deploy from source with `npx wrangler deploy`, or paste dist/worker.min.js',
      '// into the Cloudflare dashboard editor.',
    ].join('\n'),
  },
  metafile: true,
});

await build({ ...shared, outfile: minifiedFile, minify: true });

for (const warning of result.warnings ?? []) {
  console.warn(`warning: ${warning.text}`);
}

const bytes = (await readFile(outfile)).byteLength;
const minifiedBytes = (await readFile(minifiedFile)).byteLength;

console.log(`Bundled worker:       ${(bytes / 1024).toFixed(1)} kB -> dist/worker.js`);
console.log(`Minified, paste-safe: ${(minifiedBytes / 1024).toFixed(1)} kB -> dist/worker.min.js`);

/**
 * Confirm the minified bundle really survives losing every newline.
 *
 * Parsing alone is not a sufficient test: flattening a file whose first line is
 * a `//` comment turns the whole file into one comment, and an empty module
 * parses perfectly well. So import the flattened module and check the Worker's
 * fetch handler is still there.
 */
const flattened = resolve(root, 'dist/.flattened-check.mjs');
await writeFile(flattened, (await readFile(minifiedFile, 'utf8')).replace(/\r?\n/g, ' '));

let pasteSafe = false;
let failure = '';
try {
  const module = await import(pathToFileURL(flattened).href);
  if (typeof module.default?.fetch === 'function') {
    pasteSafe = true;
  } else {
    failure = 'the flattened module exports no fetch handler';
  }
} catch (error) {
  failure = error.message;
}
await rm(flattened, { force: true });

if (!pasteSafe) {
  console.error('dist/worker.min.js does not survive a newline-stripping paste:');
  console.error(`  ${failure}`);
  process.exit(1);
}
console.log('Paste-safety:         flattened to one line, the fetch handler still exports.');

await writeFile(
  resolve(root, 'dist/.build-info'),
  `built ${new Date().toISOString()}\nbytes ${bytes}\nminified ${minifiedBytes}\n`,
);

if (bytes > 900_000) {
  console.error('Bundle is unexpectedly large; check for an accidental dependency.');
  process.exit(1);
}
