/**
 * Embed the static brand assets into a TypeScript module.
 *
 * The Worker is deployed by pasting a single bundled file into the Cloudflare
 * dashboard, so it cannot rely on a separate static-asset upload. Inlining the
 * two brand images as base64 keeps that one-file deployment intact while still
 * letting the files live in public/assets/ as ordinary PNGs that can be
 * replaced, diffed and attributed.
 *
 * The generated module is committed. Run this (or `npm run build`, which calls
 * it) after changing either image.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Published path -> source file. */
const ASSETS = {
  'berkhamsted-logo.png': 'public/assets/berkhamsted-logo.png',
  'berkhamsted-wordmark.png': 'public/assets/berkhamsted-wordmark.png',
};

const entries = [];
let total = 0;

for (const [name, relative] of Object.entries(ASSETS)) {
  const bytes = await readFile(resolve(root, relative));
  total += bytes.byteLength;
  entries.push({ name, relative, base64: bytes.toString('base64'), size: bytes.byteLength });
}

const body = entries
  .map(
    (entry) =>
      `  /** ${entry.relative} (${entry.size} bytes) */\n` +
      `  '${entry.name}': '${entry.base64}',`,
  )
  .join('\n');

const source = `/**
 * Generated by scripts/embed-assets.mjs. Do not edit.
 *
 * Base64 of the files in public/assets/. Regenerate with \`npm run build\`
 * after changing an image, and commit the result.
 *
 * Licensing and attribution for these images: public/assets/ATTRIBUTION.md
 */

export const STATIC_ASSETS: Record<string, string> = {
${body}
};

/** Decode an embedded asset to bytes. */
export function decodeAsset(name: string): ArrayBuffer | null {
  const base64 = STATIC_ASSETS[name];
  if (base64 === undefined) return null;

  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes.buffer;
}
`;

await writeFile(resolve(root, 'src/worker/assets.generated.ts'), source);
console.log(
  `Embedded ${entries.length} assets (${(total / 1024).toFixed(1)} kB raw) -> src/worker/assets.generated.ts`,
);
